---
- hosts: nodes
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Adding files
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - /home/ansible/loop1
        - /home/ansible/loop2
        - /home/ansible/loop3
